"""Shared fixtures.

The synthetic clips are generated by `scripts/make_test_clips.sh` rather than
committed, because they are ~5 MB of derived data. Tests that need them skip
cleanly when they are absent, so a fresh clone still has a green suite.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[1]
BACKEND = REPO_ROOT / "backend"
CLIPS_DIR = REPO_ROOT / "benchmarks" / "clips"

if str(BACKEND) not in sys.path:
    sys.path.insert(0, str(BACKEND))


def _have_ffmpeg() -> bool:
    from shutil import which
    return bool(which("ffmpeg") and which("ffprobe"))


requires_ffmpeg = pytest.mark.skipif(not _have_ffmpeg(), reason="ffmpeg/ffprobe not installed")


@pytest.fixture(scope="session")
def clips_dir() -> Path:
    """Directory of synthetic clips, generated on first use."""
    if not _have_ffmpeg():
        pytest.skip("ffmpeg not installed")
    expected = CLIPS_DIR / "pan_constant.mp4"
    if not expected.is_file():
        script = REPO_ROOT / "scripts" / "make_test_clips.sh"
        if not script.is_file():
            pytest.skip("clip generator missing")
        subprocess.run([str(script), str(CLIPS_DIR)], check=True, timeout=600, cwd=REPO_ROOT)
    if not expected.is_file():
        pytest.skip("clip generation failed")
    return CLIPS_DIR


@pytest.fixture(scope="session")
def analyzed(clips_dir):
    """Lazily-built cache of {clip_name: (info, frames, shots, motion_result)}.

    Motion analysis costs ~1 s per clip, so it is computed once per session and
    shared across every test that needs it.
    """
    from app.tracking.shot_motion import analyze_shot_motion
    from app.video.ffprobe import probe_frames, probe_video
    from app.video.shots import detect_shots

    cache: dict[str, tuple] = {}

    def get(name: str):
        if name not in cache:
            info = probe_video(clips_dir / name)
            frames, info = probe_frames(info)
            shots, candidates = detect_shots(info, frames)
            motion = analyze_shot_motion(info, shots[0], frames, long_edge=1080)
            cache[name] = (info, frames, shots, candidates, motion)
        return cache[name]

    return get
